### ISSUE TITLE
ETL pipeline ne211.org -> HSDS 3.0?

### ISSUE THREAD

**Issue by jhannah** [211-Connect/Norse#29]
HSDS looks really cool. :) Do you already have a pipeline to get the ne211.org (for example) data into whatever persistence of HSDS? Do you want me to write one? If so, could I get a dump of the ne211.org data?

**Comment by Cskyleryoung** [comment]
Hi @jhannah, great to see you here. We actually do have their data orchestrated already. Our team, Connect 211, maintains this open source software, but also runs a service managing it for clients too. A big part of that service is creating and maintaining data orchestration. We are taking the NE211 data and transforming it into HSDS 3.0 (as of version 2.0 of this software suite).

That said, our clients maintain full ownership of their data at all times; we just develop and maintain infrastructure. If you want/need NE211 data for any purpose, you'll need to talk with the directly.

Last note: HSDS _is_ really cool. I absolutely love this data standard. Here are a few links to explore that ecosystem further:
- https://openreferral.org
- http://docs.openreferral.org/en/latest/hsds/schema_reference.html
- https://forum.openreferral.org
- And of course: https://github.com/openreferral

**Comment by jhannah** [comment]
No worries, understood. I've been doing large data transformations for decades, so was just trying to volunteer if you needed any help. Sounds like you need to keep the (public) data in-house, so me volunteering isn't helpful. :)
