### ISSUE TITLE
Allow custom header and footer links to open in new window

### ISSUE THREAD

**Issue by devcshort** [211-Connect/Norse#66]
Currently custom header and footer links only open in the current window. This is great for creating custom links to pages within the application, however external links should open in a new tab. Ideally, external links will also have an icon next to them marking them as external.

**Comment by HeetVekariya** [comment]
i would to like work in this issue.
But i want the list of links that is to be external/open in new tab.

**Comment by devcshort** [comment]
> i would to like work in this issue.
> But i want the list of links that is to be external/open in new tab.

There technically arent any links specifically. These would be custom links that someone adds through the config when setting up this app. You would just need to update the logic in the header and footer components for rendering links from the appConfig
