### ISSUE TITLE
Add `white-space: pre-line` to descriptions to properly format white space for some data.

### ISSUE THREAD

**Issue by devcshort** [211-Connect/Norse#69]
We need to properly parse line breaks for some data that gets brought in to the system. I think by adding `white-space: pre-line` to the result descriptions should fix this.

**Comment by Franqsanz** [comment]
Hello, in which file or folder should the change be made?

**Comment by devcshort** [comment]
The following files both need to get updated. Specifically the areas that hold the description/serviceDescription values

[packages/client/components/molecules/Result.tsx
](https://github.com/211-Connect/Norse/blob/main/packages/client/components/molecules/Result.tsx)

[packages/client/components/organisms/ResourceOverviewSection.tsx](https://github.com/211-Connect/Norse/blob/main/packages/client/components/organisms/ResourceOverviewSection.tsx)

**Comment by Franqsanz** [comment]
I'm not sure if Mantine has support for `whiteSpace="pre-wrap"` inside the <text> component, is it ok if I do it this way `style={{ whiteSpace: "pre-wrap" }}`?

**Comment by devcshort** [comment]
Instead of style, use Matine's built in prop `sx`. It works similar to `style`, but is parsed by the emotion library

**Comment by devcshort** [comment]
I don't think Hacktoberfest has officially started yet, so I'm going to wait to mark it as complete till I'm sure, would hate for you to not get credit for it

**Comment by Franqsanz** [comment]
No problem, thank you!

**Comment by devcshort** [comment]
> No problem, thank you!

Thank you as well 😁

**Comment by devcshort** [comment]
> No problem, thank you!

Apparently it doesn't matter if I approve it after the start date, it'll not count. Sorry 😔. I'll be adding more issues here that should be fairly easy though so stay tuned

**Comment by Franqsanz** [comment]
Do not worry there is no problem!
