### ISSUE TITLE
Make "Get Directions" button always clickable. Prompt user for address if none is currently available.

### ISSUE THREAD

**Issue by devcshort** [211-Connect/Norse#70]
The "Get Directions" button is currently grayed out if a searcher hasn't added their location for the search. We need to make this experience a bit less confusing.

We'd like to try making the get directions button **always** clickable, but then if there is no address, we should prompt users for an address.

**Comment by Saideepak01** [comment]
Hi @devcshort 

i would like to work on this issue could you assign it to me.

**Comment by rafu01** [comment]
I would like to work on this issue

**Comment by devcshort** [comment]
Hmmm, did you run the `nx run client:serve` command?
